@Restaurants.API_HostAddress = https://localhost:7087

// Restaurants CRUD Section

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants

###

@id=3
GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
  "Name": "Placite Test",
  "Description": "Just a description",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "placinte@gmail.com",
  "ContactNumber": "+37312345678",
  "City": "Chisinau",
  "Street": "Stefan Cel Mare",
  "PostalCode": "MD-1234"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/20
Content-Type: application/json

{
    "Name": "Placite Test 123",
    "Description": "Fast Food to eat every day",
    "HasDelivery": true
}

###


DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/23

###


// Dish CRUD Section

POST {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}/dishes
Content-Type: application/json

{
  "Name": "CocaCola",
  "Description": "Drink",
  "Price": 25,
  "KiloCalories": 270
}

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}/dishes/11

###

    
DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}/dishes

###


// User Identity Section

POST {{Restaurants.API_HostAddress}}/register
Content-Type: application/json

{
  "email": "testuser1@gmail.com",
  "password": "Drinkpassword!1"
}

###
 
POST {{Restaurants.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "testuser1@gmail.com",
  "password": "Drinkpassword!1"
}


###