@Restaurants.API_HostAddress = https://localhost:7087



POST {{Restaurants.API_HostAddress}}/weatherforecast/generate?count=3
Content-Type: application/json

{
  "minValue": 2,
  "maxValue": 19
}

###
