@Restaurants.API_HostAddress = https://localhost:7087

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants

###

@id=14
GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
  "Name": "Placite Test",
  "Description": "Just a description",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "placinte@gmail.com",
  "ContactNumber": "+37312345678",
  "City": "Chisinau",
  "Street": "Stefan Cel Mare",
  "PostalCode": "MD-1234"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/14
Content-Type: application/json

{
    "Name": "Placite Test 123",
    "Description": "Fast Food to eat every day",
    "HasDelivery": true
}

###


DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/900
